name: coresvc-switchboard-build

on: 
    workflow_dispatch:
    push:
        branches:
        - km/add_action

jobs:
  build-coresvc-switchboard-amd64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/coresvc-build.yaml@main
    with:
      REGISTRY: ghcr.io
      APP_NAME: coresvc-switchboard
      ANNOTATION: azure-orbital-space-sdk-coresvc-switchboard.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}

  build-coresvc-switchboard-arm64:
    permissions:
      contents: read
      packages: write

    uses: microsoft/azure-orbital-space-sdk-github-actions/.github/workflows/coresvc-build.yaml@main
    with:
      REGISTRY: ghcr.io
      APP_NAME: coresvc-switchboard
      ANNOTATION: azure-orbital-space-sdk-coresvc-switchboard.yaml
      WORKFLOW_AGENT: ubuntu-latest
      ARCHITECTURE: arm64
    secrets:
      GIT_HUB_USER_NAME: ${{ secrets.GIT_HUB_USER_NAME }}
      GIT_HUB_USER_TOKEN: ${{ secrets.GIT_HUB_USER_TOKEN }}
      SETUP_REPO_URL: ${{ secrets.SETUP_REPO_URL }}